.TH MINTSTICK "1" "April 2009" "usboot " "User Commands"

.SH NAME
usboot \- gui only application to write .img and .iso files to USB keys

.SH DESCRIPTION
.B usboot
is a graphical application to write .img and .iso files to USB keys. It can also format USB Key from a contextual menu in Cinammon and KDE desktops.

.SH "SEE ALSO"
The full documentation for
.B usboot
is maintained at http://github.com/chitwanix/usboot
.PP
Go to the project page to get access to the complete documentation.

